"""empty message

Revision ID: 2046cc845c55
Revises: 
Create Date: 2026-02-19 10:55:00.692466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2046cc845c55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_player',
    sa.Column('uid', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('class', sa.String(length=6), nullable=True),
    sa.Column('current_rank', sa.Integer(), nullable=True),
    sa.Column('highest_rank', sa.Integer(), nullable=True),
    sa.Column('total_wins', sa.Integer(), nullable=True),
    sa.Column('total_losses', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('in_ranking', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('t_challenge',
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('FK_challenger_id', sa.String(length=100), nullable=False),
    sa.Column('FK_challenged_id', sa.String(length=100), nullable=False),
    sa.Column('challenge_date', sa.Date(), nullable=True),
    sa.Column('response_date', sa.Date(), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('proposed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'completed', 'expired', name='statusenum'), nullable=True),
    sa.Column('challenger_date_confirmed', sa.Boolean(), nullable=True),
    sa.Column('challenged_date_confirmed', sa.Boolean(), nullable=True),
    sa.Column('challenger_wants_cancel', sa.Boolean(), nullable=True),
    sa.Column('challenged_wants_cancel', sa.Boolean(), nullable=True),
    sa.Column('challenger_result_confirmed', sa.Boolean(), nullable=True),
    sa.Column('challenged_result_confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['FK_challenged_id'], ['t_player.uid'], ),
    sa.ForeignKeyConstraint(['FK_challenger_id'], ['t_player.uid'], ),
    sa.PrimaryKeyConstraint('challenge_id')
    )
    op.create_table('t_match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=3), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('FK_challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FK_challenge_id'], ['t_challenge.challenge_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('t_notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('FK_challenge_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('challenge', 'match_result', 'rank_change', 'etc', name='notificationtypeenum'), nullable=True),
    sa.Column('FK_recipient_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['FK_challenge_id'], ['t_challenge.challenge_id'], ),
    sa.ForeignKeyConstraint(['FK_recipient_id'], ['t_player.uid'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_notification')
    op.drop_table('t_match')
    op.drop_table('t_challenge')
    op.drop_table('t_player')
    # ### end Alembic commands ###
