"""update db

Revision ID: 444047f4a721
Revises: a5901bc16361
Create Date: 2026-01-20 19:20:36.232515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444047f4a721'
down_revision = 'a5901bc16361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposed_date', sa.Date(), nullable=True))

    with op.batch_alter_table('t_match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_match', schema=None) as batch_op:
        batch_op.drop_column('match_date')

    with op.batch_alter_table('t_challenge', schema=None) as batch_op:
        batch_op.drop_column('proposed_date')

    # ### end Alembic commands ###
