"""Replace active with last_active and add blocked_until

Revision ID: 626ae23106b0
Revises: 
Create Date: 2025-11-19 08:10:49.419068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626ae23106b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('blocked_until', sa.DateTime(), nullable=True))
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('blocked_until')
        batch_op.drop_column('last_active')

    # ### end Alembic commands ###
