"""redo 

Revision ID: 6cf2ace9d566
Revises: faaddd275cbd
Create Date: 2026-01-07 08:57:50.658012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf2ace9d566'
down_revision = 'faaddd275cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenger_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('challenged_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_match', schema=None) as batch_op:
        batch_op.drop_column('challenged_confirmed')
        batch_op.drop_column('challenger_confirmed')

    # ### end Alembic commands ###
